---
title: "Sandhya Anand Kumar MBA"
output: html_document
---


[sandhyaphr7@gmail.com](mailto:sandhyaphr7@gmail.com)| [LinkedIn Profile](http://www.linkedin.com/in/sandyanand/)

**Microsoft Certified Data Science professional** with Master&#39;s degree in Business Management, passionate in Data Science and Analytics including Machine Learning, Data Mining and Statistical Analysis.

###**Technology Skills**###

T-Sql. Python, R Programming, Azure  Machine Learning, Power BI,SAP HCM

R Libraries: dplyr, ggplot2, corrplot, Hmisc, RcmdrMisc, VIM, caret, mice and random Forest

###**Education**###

**Master of Business Administration**** ICFAI University**, INDIA

**Bachelor of Science** INDIA

###**Certifications**###

**MICROSOFT PROFESSIONAL PROGRAM IN DATA SCIENCE (Mar. 2017-Oct.2017)**

**Microsoft Certification in Analyzing and Visualizing Data with Power BI**

**Microsoft Certification in Programming with R for Data Science**

**Microsoft Certification in Applied Machine Learning**

**Microsoft Certification in Essential Statistics for Data Analysis using Excel**

**Microsoft Certification in Querying with Transact-SQL**

**Microsoft Certification in Data Science Orientation**

**Algorithm and Data structure: KAL Academy**

**PHR Certification-HRCI**

**SHRM-CP Certification-SHRM**

**SAP ERP Human Capital management** ECC 6.0 training, Cognizant Technologies Ltd. India

###**Skills Summary**###
- Analyze complex data sets, data cleaning and data manipulation and transformation using R programming   
- Perform statistical analysis using Excel and R Programming  
- Visualizing data (Histogram, Density plots, Scatter plots, box plots) using Power BI dashboards, ggplot in R  
- Querying data using T-SQL   
- Identifying correlations and intercorrelations in R  
- Build predictive models (linear, logistical, Random forest, Boosted models) in R and Azure ML and Testing and evaluating models. 


###**Projects**###

####**Data Science Capstone Project -Microsoft Professional Program**####

The goal of this capstone project is to predict the future earnings of the students, a set number of years after they initially enrolled in the college **.**

- There were 298 features across 17,107 samples. Summary Statistics and exploratory analysis were used for understanding the features and their impact on output variable. Out of these 298 features, 198 were categorical features and 100 numerical features that were evaluated.
- Feature selection was done to identify variables that are key for the model. Correlation and Inter correlation was used to filter out numerical features, and Chi-square test was used to identify key categorical features. Final feature set contained 11 independent variables.
- Data exploration was done using ggplots (Bar plots, Line plots) and corrplot
- Using the R programming language, various models were built (Linear, Random forest, Boosted Random forest). The model parameters were fine-tuned and model with least RMSE (Root Mean Square Error) was selected.



###**Professional Experience**###

Resigned my recruiter job for a career in Data Analytics.

**Interned and Worked as a Technical Recruiter in the following companies between May 2013 - Feb.-2017**

### **Allyis, Horizon Consulting,MyNetwork,Gigawatt**###

- Identified potential candidates using candidate referrals, networking, internal database, LinkedIn, Dice, Monster and other web sourcing tools.
- Recruiting contract, contract-to-hire professionals from Jr. Level to senior level.
- Responsible for making initial contact with candidates including developing a relationship and establishing credibility, pitching job opportunities, and assessing candidates&#39; personality and technical experience. Perform detailed reference checking and reference analysis on selected candidates and review results with hiring managers.
- Extended offers of employment to selected candidates within the guidelines of compensation policy.
- Managing the presentation, selection, offer, negotiation, closing, and administrative components involved in full life cycle recruiting.
- Recruiting: Jr. Software Engineers, .Net Developers, UI developers, Front end Developers, Software Test Engineers, Data Analyst, BI Developers, Buy desk Analysts, Marketing Data analysts, Business Analysts, Accounts PM, Java/Hadoop developers, Content Schedulers etc.

### [**SAP HR Associate (Internship)**](https://www.linkedin.com/search/results/index/?keywords=Simbiz%20Software%20Solutions)

#### [Simbiz Software Solutions](https://www.linkedin.com/search/results/index/?keywords=Simbiz%20Software%20Solutions) [                                                               ](https://www.linkedin.com/search/results/index/?keywords=Simbiz%20Software%20Solutions) [May 2012 - Aug 2012](https://www.linkedin.com/search/results/index/?keywords=Simbiz%20Software%20Solutions)

[ ](https://www.linkedin.com/search/results/index/?keywords=Simbiz%20Software%20Solutions) [Location](https://www.linkedin.com/search/results/index/?keywords=Simbiz%20Software%20Solutions) [Michigan, USA](https://www.linkedin.com/search/results/index/?keywords=Simbiz%20Software%20Solutions)

- Our five-member project team were involved in successful customization and configuration of different SAP HR sub modules like Personnel Administration, Organization management, Payroll, Time management, Benefits, and Personnel development.

- My main focus was on Personnel administration and Organizational management.   

**Main job responsibilities:**   

- Defined the enterprise structure, personnel structure, and pay scale structure. 
- Defined Personnel data and payroll data for administrative and payroll perspective. 
- Defined pay scale types, areas, group levels and salary ranges, setting up of the payroll period, defining
pay scale reclassification. 
- Maintained Employee Data edited Info types, familiar with Fast Entry and Dynamic Actions. 
- Defined the authorizations for Master data maintenance and Personnel number assignment for 
employees being hired. 
- Configured employee subgroup grouping for the personnel calculation rule to allow one wage type to
be processed in different ways in payroll accounting. 
- Created and maintained the Organizational structure objects like the organizational unit, jobs, and
positions. 
- Configured the Info groups for each of the objects like Organization Units, Jobs, and Positions etc. 
- Used feature PLOGI to integrate Organizational Management with Personnel Administration in order
to automatically transfer data between modules. 

